baseURL: https://eustomadew.github.io

languageCode: en-us
# title: "Aqua Eustoma"
# theme: "toha"
title: "eustomaqua" # "Yj Bian" # "Yijun Bian"
theme: "mainroad"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1
  # de:
  #   languageName: Deutsch # German
  #   weight: 2
  # fr:
  #   languageName: français # Franch
  #   weight: 3

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # GitHub repo URL of your site
  gitRepo: https://github.com/eustomadew/eustomadew.github.io

  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: false # true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false

Author:
  name: eustomaqua # Yijun Bian
  bio: "Ph.D. at USTC"
  avatar: "assets/images/eustomaqua.jpg"
Params:
  opengraph: true
  readmore: false
  authorbox: true
  pager: true
  post_meta: ["date", "categories"]
  logo:
    # image: "eustomaqua.jpg"
    title: "Yijun Bian"
    subtitle: Open science participant # participator
  googleFontsLink: "https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400&display=swap"
  style:
    vars:
      # highlightColor: "#3CB371" # "#00FA9A" # "#48D1CC" # "#40E0D0"
      highlightColor: "#4169E1" # "#e22d30"
      fontFamilyPrimary: "'Roboto', sans-serif"
      # fontFamilyPrimary: "''Alkalami', sans-serif"
      # fontFamilyPrimary: "'EB Garamond', sans-serif" # serif
      # fontFamilyPrimary: "'Libre Baskerville', monospace" # display
  thumbnail:
    src: "eustomaqua.jpg"
    title: "Yj Bian"
    visibility: ["list", "post"]
  # sidebar: "left" # Enable sidebar (on the left side) per page
  menu: ["main", "side", "footer"]

#  sidebar:
#    home: "right"
#    list: "right"
#    single: "right"
#    sidebar: "left"
#    widgets:
#      - "search"
#      # - "recent"
#      # - "categories"
#      # - "taglist"
#      - "social"
#      # - "languages"
#  widgets:
#    recent_num: 5
#    categories_counter: false
#    tags_counter: false
#    social:
#      email: "yjbian@mail.ustc.edu.cn"
#      linkedin: "yijunbian"
#      github: "eustomaqua"
#      # custom:
#      #   title: "YouTube"
#      #   url: "https://youtube.com/user/username"
#      #   icon: "youtube.svg"
#      # gitlab: "username"
#      # facebook: "username"
#      # twitter: "username"
#      # instagram: "username"
#      # telegram: "username"
#      # bitbucket: "username"

#  sidebar:
#    home: "right"   # Configure layout for home page
#    list: "right"   # Configure layout for list pages
#    single: "right" # Configure layout for single pages
#    # Enable widgets in given order
#    widgets: ["search", "recent", "categories", "taglist"]
#  widgets:
#    recent_num: 5 # Set the number of articles in the "Recent articles" widget
#    tags_counter: false # Enable counter for each tag in "Tags" widget
